export const FETCH_SESSION_REQUESTED = 'FETCH_SESSION_REQUESTED';
export const FETCH_SESSION_SUCCEEDED = 'FETCH_SESSION_SUCCEEDED';
export const FETCH_LOGIN_REQUESTED = 'FETCH_LOGIN_REQUESTED';
export const FETCH_LOGIN_SUCCEEDED = 'FETCH_LOGIN_SUCCEEDED';
export const LOGOUT = 'LOGOUT';
